name: CI/CD â€“ Application with Docker

on:
  push:
    branches: [feature/*]
    types: [push]

jobs:
  build-test-push:
    name: Build, Test and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout source code
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches full history for better caching/context

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Cache Docker layers
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-

      # 4. Extract metadata
      - name: Extract metadata
        id: meta
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> "$GITHUB_OUTPUT"
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      # 5. Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 6. Build and push dev image
      - name: Build and push development/feature image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_PROJECT_NAME }}:${GITHUB_REF##*/}
            ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKERHUB_PROJECT_NAME }}:${{ steps.meta.outputs.SHORT_SHA }}
          cache-from: type=local,src=/tmp/.buildx-cache

# this is for after we've figured out the feature/ tree
# in the nginx config
#       # 7. copy docker compose to tov
#       - name: Copy files via SSH
#         uses: appleboy/scp-action@v1
#         with:
#           host: ${{ secrets.DEPLOY_SERVER }}
#           username: ${{ secrets.DEPLOY_USER }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           source: "docker-compose.yml"
#           target: "."
# 
#       # 8. ssh to tov & docker-compose pull
#       - name: Deploy with SSH Action
#         uses: appleboy/ssh-action@v1.0.0
#         with:
#           host: ${{ secrets.DEPLOY_SERVER }}
#           username: ${{ secrets.DEPLOY_USER }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           script: |
#             touch i-was-here.txt
#             docker-compose pull
#             # Run other deployment commands
